Models/ErrorViewModel.cs
using System;

namespace MenuDishApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Ingredient/Ingredient.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MenuDishApp.Models.Ingredients
{
    public class Ingredients
    {
        public int ID { get; set; }
        public string Ingredient { get; set; }
    }
}

Models/MenuDish/MenuDish.cs
using System.ComponentModel.DataAnnotations;

namespace MenuDishApp.Models.MenuDish
{
    public class MenuDish
    {
        public int ID { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        [DataType(DataType.Currency)]
        public double Price { get; set; }
        public bool Family { get; set; }

        public string DishType { get; set; }
    }
}

Controllers/HomeController.cs
using MenuDishApp.Data;
using MenuDishApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MenuDishApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IngredientContext _context;
        private readonly MenuDishContext _contextMenu;

        public HomeController(ILogger<HomeController> logger, IngredientContext context, MenuDishContext contextMenu)
        {
            _logger = logger;
            _context = context;
            _contextMenu = contextMenu;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Ingredients.ToListAsync());
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult Test()
        {
            return View();
        }



        public async Task<IActionResult> Result(string[] checkbox)
        {

            var ingredients = from i in _contextMenu.MenuDish
                              select i;
            bool excludeInclude = (checkbox.Any() && checkbox[^1] == "on") ? true : false;
            foreach (var item in checkbox)
            {
                if (!String.IsNullOrEmpty(item))
                {
                    if (excludeInclude)
                        ingredients = ingredients.Where(s => s.Description.Contains(item));
                    else
                        ingredients = ingredients.Where(s => !s.Description.Contains(item));
                }
            }

            ingredients = ingredients.OrderBy(i => i.Description);
            //ingredients = from i in ingredients
            //              orderby i.DishType
            //              select i;


            return View(await ingredients.ToListAsync());
        }
    }
}

Controllers/MenuDishesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MenuDishApp.Data;
using MenuDishApp.Models.MenuDish;

namespace MenuDishApp.Controllers
{
    public class MenuDishesController : Controller
    {
        private readonly MenuDishContext _context;

        public MenuDishesController(MenuDishContext context)
        {
            _context = context;
        }

        // GET: MenuDishes
        public async Task<IActionResult> Index()
        {
            return View(await _context.MenuDish.ToListAsync());
        }

        // GET: MenuDishes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menuDish = await _context.MenuDish
                .FirstOrDefaultAsync(m => m.ID == id);
            if (menuDish == null)
            {
                return NotFound();
            }

            return View(menuDish);
        }

        // GET: MenuDishes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MenuDishes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Number,Name,Description,Price,Family")] MenuDish menuDish)
        {
            if (ModelState.IsValid)
            {
                _context.Add(menuDish);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(menuDish);
        }

        // GET: MenuDishes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menuDish = await _context.MenuDish.FindAsync(id);
            if (menuDish == null)
            {
                return NotFound();
            }
            return View(menuDish);
        }

        // POST: MenuDishes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Number,Name,Description,Price,Family")] MenuDish menuDish)
        {
            if (id != menuDish.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(menuDish);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MenuDishExists(menuDish.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(menuDish);
        }

        // GET: MenuDishes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menuDish = await _context.MenuDish
                .FirstOrDefaultAsync(m => m.ID == id);
            if (menuDish == null)
            {
                return NotFound();
            }

            return View(menuDish);
        }

        // POST: MenuDishes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var menuDish = await _context.MenuDish.FindAsync(id);
            _context.MenuDish.Remove(menuDish);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MenuDishExists(int id)
        {
            return _context.MenuDish.Any(e => e.ID == id);
        }
    }
}

Views/Home/Index.cshtml
@model IEnumerable<MenuDishApp.Models.Ingredients.Ingredients>

@{
    ViewData["Title"] = "Home Page";
}
<script src="~/js/site.js" type="text/javascript"></script>

<div class="text-center">
    <h1 class="display-4">Velkommen</h1>
</div>

<div id="display"></div>

<h2 class="text-center">Her har du mulighed for at til- eller fravælge ingredienser</h2>
<br />
<br />

<form asp-controller="Home" asp-action="Result" method="get">
    <div>
        <ul class="list-unstyled row">
            @foreach (var item in Model)
            {
                <li class="col-md-3 col-xs-6">
                    <label>
                        <input type="checkbox" name="checkbox" value="@item.Ingredient" /> @item.Ingredient
                    </label>
                </li>
            }
        </ul>
        <div>
            <label><input type="checkbox" name="checkbox" checked="checked"/> Tilvalg</label>
        </div>
        <input type="submit" class="btn btn-primary" value="Sorter" />

    </div>
</form>

Views/Home/Result.cshtml
@model IEnumerable<MenuDishApp.Models.MenuDish.MenuDish>

@{
    ViewData["Title"] = "Result";
}

<h1>Result</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DishType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DishType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                @*<td>
                        <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                    </td>*@
            </tr>
        }
    </tbody>
</table>
<a href="/Home/Index" class="btn btn-primary">Tilbage</a>

Views/Home/Test.cshtml
@{
    ViewData["Title"] = "Test";
}
<script src="~/js/site.js" type="text/javascript"></script>

<h1>Test</h1>

<div id="testMore"></div>

<script type="text/javascript">
    MegaTest();
</script>

Views/MenuDishes/Create.cshtml
@model MenuDishApp.Models.MenuDish.MenuDish

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>MenuDish</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Family" /> @Html.DisplayNameFor(model => model.Family)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/MenuDishes/Delete.cshtml
@model MenuDishApp.Models.MenuDish.MenuDish

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MenuDish</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Number)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Number)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Family)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Family)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/MenuDishes/Details.cshtml
@model MenuDishApp.Models.MenuDish.MenuDish

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>MenuDish</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Number)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Number)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Family)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Family)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/MenuDishes/Edit.cshtml
@model MenuDishApp.Models.MenuDish.MenuDish

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>MenuDish</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Family" /> @Html.DisplayNameFor(model => model.Family)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/MenuDishes/Index.cshtml
@model IEnumerable<MenuDishApp.Models.MenuDish.MenuDish>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Number)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Family)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Number)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Family)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Menu Dish App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Menu Dish App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @*<partial name="_LoginPartial" />*@
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>*@
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="MenuDishes" asp-action="Index">Menu Dishes</a>
                            </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - MenuDishApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>